project:
  type: website

website:
  title: "Thoughts, Code and Mischief"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mehulfollytobevice
format:
  html:
    theme: cosmo
    css: styles.css



